//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 02.11.2022 14:59:13
namespace OData.Sample.WebApi
{
    /// <summary>
    /// There are no comments for CountriesContext in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CountriesContext")]
    public partial class CountriesContext : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CountriesContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public CountriesContext(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new CountriesContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public CountriesContext(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "OData.Sample.WebApi", "OData.Sample.WebApi");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("OData.Sample.WebApi", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("OData.Sample.WebApi.", originalNameAttribute.OriginalName);
                }
                return string.Concat("OData.Sample.WebApi.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for WorldRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<WorldRegion> WorldRegions
        {
            get
            {
                if ((this._WorldRegions == null))
                {
                    this._WorldRegions = base.CreateQuery<WorldRegion>("WorldRegions");
                }
                return this._WorldRegions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<WorldRegion> _WorldRegions;
        /// <summary>
        /// There are no comments for CountryRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<CountryRegion> CountryRegions
        {
            get
            {
                if ((this._CountryRegions == null))
                {
                    this._CountryRegions = base.CreateQuery<CountryRegion>("CountryRegions");
                }
                return this._CountryRegions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<CountryRegion> _CountryRegions;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Countries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<Country> Countries
        {
            get
            {
                if ((this._Countries == null))
                {
                    this._Countries = base.CreateQuery<Country>("Countries");
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<Country> _Countries;
        /// <summary>
        /// There are no comments for WorldRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToWorldRegions(WorldRegion worldRegion)
        {
            base.AddObject("WorldRegions", worldRegion);
        }
        /// <summary>
        /// There are no comments for CountryRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCountryRegions(CountryRegion countryRegion)
        {
            base.AddObject("CountryRegions", countryRegion);
        }
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCountries(Country country)
        {
            base.AddObject("Countries", country);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ODataSampleServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for WorldRegionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegionSingle")]
    public partial class WorldRegionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<WorldRegion>
    {
        /// <summary>
        /// Initialize a new WorldRegionSingle object.
        /// </summary>
        public WorldRegionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new WorldRegionSingle object.
        /// </summary>
        public WorldRegionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new WorldRegionSingle object.
        /// </summary>
        public WorldRegionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<WorldRegion> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CountryRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegions")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.CountryRegion> CountryRegions
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CountryRegions == null))
                {
                    this._CountryRegions = Context.CreateQuery<global::OData.Sample.WebApi.CountryRegion>(GetPath("CountryRegions"));
                }
                return this._CountryRegions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.CountryRegion> _CountryRegions;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Countries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> Countries
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Countries == null))
                {
                    this._Countries = Context.CreateQuery<global::OData.Sample.WebApi.Country>(GetPath("Countries"));
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> _Countries;
    }
    /// <summary>
    /// There are no comments for WorldRegion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("WorldRegions")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegion")]
    public partial class WorldRegion : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new WorldRegion object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static WorldRegion CreateWorldRegion(int ID)
        {
            WorldRegion worldRegion = new WorldRegion();
            worldRegion.Id = ID;
            return worldRegion;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ISO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ISO")]
        public virtual string ISO
        {
            get
            {
                return this._ISO;
            }
            set
            {
                this.OnISOChanging(value);
                this._ISO = value;
                this.OnISOChanged();
                this.OnPropertyChanged("ISO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ISO;
        partial void OnISOChanging(string value);
        partial void OnISOChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NameGER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NameGER")]
        public virtual string NameGER
        {
            get
            {
                return this._NameGER;
            }
            set
            {
                this.OnNameGERChanging(value);
                this._NameGER = value;
                this.OnNameGERChanged();
                this.OnPropertyChanged("NameGER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NameGER;
        partial void OnNameGERChanging(string value);
        partial void OnNameGERChanged();
        /// <summary>
        /// There are no comments for Property CountryRegions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegions")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.CountryRegion> CountryRegions
        {
            get
            {
                return this._CountryRegions;
            }
            set
            {
                this.OnCountryRegionsChanging(value);
                this._CountryRegions = value;
                this.OnCountryRegionsChanged();
                this.OnPropertyChanged("CountryRegions");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.CountryRegion> _CountryRegions = new global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.CountryRegion>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCountryRegionsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.CountryRegion> value);
        partial void OnCountryRegionsChanged();
        /// <summary>
        /// There are no comments for Property Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Countries")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> Countries
        {
            get
            {
                return this._Countries;
            }
            set
            {
                this.OnCountriesChanging(value);
                this._Countries = value;
                this.OnCountriesChanged();
                this.OnPropertyChanged("Countries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> _Countries = new global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCountriesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> value);
        partial void OnCountriesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CountryRegionSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegionSingle")]
    public partial class CountryRegionSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<CountryRegion>
    {
        /// <summary>
        /// Initialize a new CountryRegionSingle object.
        /// </summary>
        public CountryRegionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CountryRegionSingle object.
        /// </summary>
        public CountryRegionSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CountryRegionSingle object.
        /// </summary>
        public CountryRegionSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<CountryRegion> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for WorldRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegion")]
        public virtual global::OData.Sample.WebApi.WorldRegionSingle WorldRegion
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._WorldRegion == null))
                {
                    this._WorldRegion = new global::OData.Sample.WebApi.WorldRegionSingle(this.Context, GetPath("WorldRegion"));
                }
                return this._WorldRegion;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.WorldRegionSingle _WorldRegion;
        /// <summary>
        /// There are no comments for Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Countries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> Countries
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Countries == null))
                {
                    this._Countries = Context.CreateQuery<global::OData.Sample.WebApi.Country>(GetPath("Countries"));
                }
                return this._Countries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> _Countries;
    }
    /// <summary>
    /// There are no comments for CountryRegion in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("CountryRegions")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegion")]
    public partial class CountryRegion : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CountryRegion object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static CountryRegion CreateCountryRegion(int ID)
        {
            CountryRegion countryRegion = new CountryRegion();
            countryRegion.Id = ID;
            return countryRegion;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property ISO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ISO")]
        public virtual string ISO
        {
            get
            {
                return this._ISO;
            }
            set
            {
                this.OnISOChanging(value);
                this._ISO = value;
                this.OnISOChanged();
                this.OnPropertyChanged("ISO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ISO;
        partial void OnISOChanging(string value);
        partial void OnISOChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NameGER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NameGER")]
        public virtual string NameGER
        {
            get
            {
                return this._NameGER;
            }
            set
            {
                this.OnNameGERChanging(value);
                this._NameGER = value;
                this.OnNameGERChanged();
                this.OnPropertyChanged("NameGER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NameGER;
        partial void OnNameGERChanging(string value);
        partial void OnNameGERChanged();
        /// <summary>
        /// There are no comments for Property WorldRegionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegionId")]
        public virtual global::System.Nullable<int> WorldRegionId
        {
            get
            {
                return this._WorldRegionId;
            }
            set
            {
                this.OnWorldRegionIdChanging(value);
                this._WorldRegionId = value;
                this.OnWorldRegionIdChanged();
                this.OnPropertyChanged("WorldRegionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _WorldRegionId;
        partial void OnWorldRegionIdChanging(global::System.Nullable<int> value);
        partial void OnWorldRegionIdChanged();
        /// <summary>
        /// There are no comments for Property WorldRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegion")]
        public virtual global::OData.Sample.WebApi.WorldRegion WorldRegion
        {
            get
            {
                return this._WorldRegion;
            }
            set
            {
                this.OnWorldRegionChanging(value);
                this._WorldRegion = value;
                this.OnWorldRegionChanged();
                this.OnPropertyChanged("WorldRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.WorldRegion _WorldRegion;
        partial void OnWorldRegionChanging(global::OData.Sample.WebApi.WorldRegion value);
        partial void OnWorldRegionChanged();
        /// <summary>
        /// There are no comments for Property Countries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Countries")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> Countries
        {
            get
            {
                return this._Countries;
            }
            set
            {
                this.OnCountriesChanging(value);
                this._Countries = value;
                this.OnCountriesChanged();
                this.OnPropertyChanged("Countries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> _Countries = new global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnCountriesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::OData.Sample.WebApi.Country> value);
        partial void OnCountriesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CountrySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CountrySingle")]
    public partial class CountrySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Country>
    {
        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CountrySingle object.
        /// </summary>
        public CountrySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Country> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CountryRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegion")]
        public virtual global::OData.Sample.WebApi.CountryRegionSingle CountryRegion
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CountryRegion == null))
                {
                    this._CountryRegion = new global::OData.Sample.WebApi.CountryRegionSingle(this.Context, GetPath("CountryRegion"));
                }
                return this._CountryRegion;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.CountryRegionSingle _CountryRegion;
        /// <summary>
        /// There are no comments for WorldRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegion")]
        public virtual global::OData.Sample.WebApi.WorldRegionSingle WorldRegion
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._WorldRegion == null))
                {
                    this._WorldRegion = new global::OData.Sample.WebApi.WorldRegionSingle(this.Context, GetPath("WorldRegion"));
                }
                return this._WorldRegion;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.WorldRegionSingle _WorldRegion;
    }
    /// <summary>
    /// There are no comments for Country in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.EntitySet("Countries")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Country")]
    public partial class Country : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Country object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Country CreateCountry(int ID)
        {
            Country country = new Country();
            country.Id = ID;
            return country;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DisplayName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DisplayName")]
        public virtual string DisplayName
        {
            get
            {
                return this._DisplayName;
            }
            set
            {
                this.OnDisplayNameChanging(value);
                this._DisplayName = value;
                this.OnDisplayNameChanged();
                this.OnPropertyChanged("DisplayName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DisplayName;
        partial void OnDisplayNameChanging(string value);
        partial void OnDisplayNameChanged();
        /// <summary>
        /// There are no comments for Property DisplayNameGER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DisplayNameGER")]
        public virtual string DisplayNameGER
        {
            get
            {
                return this._DisplayNameGER;
            }
            set
            {
                this.OnDisplayNameGERChanging(value);
                this._DisplayNameGER = value;
                this.OnDisplayNameGERChanged();
                this.OnPropertyChanged("DisplayNameGER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DisplayNameGER;
        partial void OnDisplayNameGERChanging(string value);
        partial void OnDisplayNameGERChanged();
        /// <summary>
        /// There are no comments for Property EU in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EU")]
        public virtual string EU
        {
            get
            {
                return this._EU;
            }
            set
            {
                this.OnEUChanging(value);
                this._EU = value;
                this.OnEUChanged();
                this.OnPropertyChanged("EU");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EU;
        partial void OnEUChanging(string value);
        partial void OnEUChanged();
        /// <summary>
        /// There are no comments for Property EWR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EWR")]
        public virtual string EWR
        {
            get
            {
                return this._EWR;
            }
            set
            {
                this.OnEWRChanging(value);
                this._EWR = value;
                this.OnEWRChanged();
                this.OnPropertyChanged("EWR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EWR;
        partial void OnEWRChanging(string value);
        partial void OnEWRChanged();
        /// <summary>
        /// There are no comments for Property ISO2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ISO2")]
        public virtual string ISO2
        {
            get
            {
                return this._ISO2;
            }
            set
            {
                this.OnISO2Changing(value);
                this._ISO2 = value;
                this.OnISO2Changed();
                this.OnPropertyChanged("ISO2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ISO2;
        partial void OnISO2Changing(string value);
        partial void OnISO2Changed();
        /// <summary>
        /// There are no comments for Property ISO3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ISO3")]
        public virtual string ISO3
        {
            get
            {
                return this._ISO3;
            }
            set
            {
                this.OnISO3Changing(value);
                this._ISO3 = value;
                this.OnISO3Changed();
                this.OnPropertyChanged("ISO3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ISO3;
        partial void OnISO3Changing(string value);
        partial void OnISO3Changed();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NameGER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NameGER")]
        public virtual string NameGER
        {
            get
            {
                return this._NameGER;
            }
            set
            {
                this.OnNameGERChanging(value);
                this._NameGER = value;
                this.OnNameGERChanged();
                this.OnPropertyChanged("NameGER");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _NameGER;
        partial void OnNameGERChanging(string value);
        partial void OnNameGERChanged();
        /// <summary>
        /// There are no comments for Property CountryRegionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegionId")]
        public virtual global::System.Nullable<int> CountryRegionId
        {
            get
            {
                return this._CountryRegionId;
            }
            set
            {
                this.OnCountryRegionIdChanging(value);
                this._CountryRegionId = value;
                this.OnCountryRegionIdChanged();
                this.OnPropertyChanged("CountryRegionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _CountryRegionId;
        partial void OnCountryRegionIdChanging(global::System.Nullable<int> value);
        partial void OnCountryRegionIdChanged();
        /// <summary>
        /// There are no comments for Property WorldRegionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegionId")]
        public virtual global::System.Nullable<int> WorldRegionId
        {
            get
            {
                return this._WorldRegionId;
            }
            set
            {
                this.OnWorldRegionIdChanging(value);
                this._WorldRegionId = value;
                this.OnWorldRegionIdChanged();
                this.OnPropertyChanged("WorldRegionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _WorldRegionId;
        partial void OnWorldRegionIdChanging(global::System.Nullable<int> value);
        partial void OnWorldRegionIdChanged();
        /// <summary>
        /// There are no comments for Property CountryRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CountryRegion")]
        public virtual global::OData.Sample.WebApi.CountryRegion CountryRegion
        {
            get
            {
                return this._CountryRegion;
            }
            set
            {
                this.OnCountryRegionChanging(value);
                this._CountryRegion = value;
                this.OnCountryRegionChanged();
                this.OnPropertyChanged("CountryRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.CountryRegion _CountryRegion;
        partial void OnCountryRegionChanging(global::OData.Sample.WebApi.CountryRegion value);
        partial void OnCountryRegionChanged();
        /// <summary>
        /// There are no comments for Property WorldRegion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WorldRegion")]
        public virtual global::OData.Sample.WebApi.WorldRegion WorldRegion
        {
            get
            {
                return this._WorldRegion;
            }
            set
            {
                this.OnWorldRegionChanging(value);
                this._WorldRegion = value;
                this.OnWorldRegionChanged();
                this.OnPropertyChanged("WorldRegion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::OData.Sample.WebApi.WorldRegion _WorldRegion;
        partial void OnWorldRegionChanging(global::OData.Sample.WebApi.WorldRegion value);
        partial void OnWorldRegionChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.WorldRegion as global::OData.Sample.WebApi.WorldRegionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::OData.Sample.WebApi.WorldRegionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.WorldRegion> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::OData.Sample.WebApi.WorldRegionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.WorldRegion as global::OData.Sample.WebApi.WorldRegionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::OData.Sample.WebApi.WorldRegionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.WorldRegion> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::OData.Sample.WebApi.WorldRegionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.CountryRegion as global::OData.Sample.WebApi.CountryRegionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::OData.Sample.WebApi.CountryRegionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.CountryRegion> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::OData.Sample.WebApi.CountryRegionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.CountryRegion as global::OData.Sample.WebApi.CountryRegionSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::OData.Sample.WebApi.CountryRegionSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.CountryRegion> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::OData.Sample.WebApi.CountryRegionSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.Country as global::OData.Sample.WebApi.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::OData.Sample.WebApi.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::OData.Sample.WebApi.CountrySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::OData.Sample.WebApi.Country as global::OData.Sample.WebApi.CountrySingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::OData.Sample.WebApi.CountrySingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OData.Sample.WebApi.Country> _source,
            int id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::OData.Sample.WebApi.CountrySingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
