<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OData.Sample.Client</AssemblyName>
    <RootNamespace>OData.Sample.Client</RootNamespace>
    <Title>OData.Sample.Client</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Connected Services\ODataSampleService\ODataSampleServiceCsdl.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Connected Services\ODataSampleService\ODataSampleServiceCsdl.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoBogus" Version="2.13.1" />
    <PackageReference Include="Microsoft.OData.Client" Version="8.0.2" />
    <PackageReference Include="Microsoft.OData.Core" Version="8.0.2" />
    <PackageReference Include="Microsoft.OData.Edm" Version="8.0.2" />
    <PackageReference Include="Microsoft.Spatial" Version="8.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="IDisposableAnalyzers" Version="4.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="17.11.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
